### PR TITLE
Run all tasks as System instead of current user

### PR DESCRIPTION
**Pull request by SunsetTechuila**
It will completely hide PoSh window. Running PoSh script as current user show Posh window to this user for a second.

### CODE REVIEW

**Comment by farag2** [comment]
Unfortunately, I've already tested with this configuration. Some process don't work at all. So this is the price to make it all working. :)

**Comment by SunsetTechuila** [comment]
sad, seeing flickering windows is annoying, even if they appear once a month

**Comment by farag2** [comment]
Sorry for bad news. I appreciate your efforts to improve the code.

**Comment by SunsetTechuila** [comment]
maybe try some open source hider app?

**Comment by farag2** [comment]
I do not think it's actually necessary to hide. Also the ideology of the script is to use only pure code instead of using 3rd party apps.

**Comment by SunsetTechuila** [comment]
Ah, I see now. Dialog will also show to the System and user won't see it. But I've googled [this](https://learn.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotificationmanager.getforuser). Maybe I will find and implement a solution later.

**Comment by SunsetTechuila** [comment]
And all the user-specific variables can be hardcoded in the tasks, so it won't be matter as which user they will run

**Comment by SunsetTechuila** [comment]
impossible

**Comment by farag2** [comment]
Well... So it goes)

**Comment by SunsetTechuila** [comment]
will you reject option to use wscript (if disabled - enable then disable after run all tasks)?

**Comment by farag2** [comment]
Bad approach. Very bad. There's no need to to such things just to hide that damned window. It's not worth.

**Comment by SunsetTechuila** [comment]
I understand why using wscript is bad, but sheduled jobs look like exactly what we need, did you try they?

**Comment by farag2** [comment]
Em, try scheduled jobs? I cannot get you idea.

**Comment by SunsetTechuila** [comment]
W k. Qln ..

**Pull request closed without merging**
