### PR TITLE
#430 | DefenderServices check (edge-cases)

### LINKED ISSUE #430: DefenderServices check (edge-cases)
### Discussed in https://github.com/farag2/Sophia-Script-for-Windows/discussions/425

<div type='discussions-op-text'>

<sup>Originally posted by **alan-null** December 13, 2022</sup>
Didn't know if I should start a discussion or report it as an issue so let me know how do you want to handle code/logic related things in the future (issues or discussion first).

I am currently reading the whole code and found this

https://github.com/farag2/Sophia-Script-for-Windows/blob/6692e83d68e7421c82d90910d52e91db7db6c69a/src/Sophia_Script_for_Windows_10/Module/Sophia.psm1#L300-L307

So there are 3 services that script checks via Foreach
- Windefend
- SecurityHealthService
- wscsvc

When we have following state:
```
Status   Name               DisplayName
------   ----               -----------
Running  Windefend          Microsoft Defender Antivirus Service
Running  SecurityHealthS... Windows Security Service
Running  wscsvc             Security Center
```
everything will work fine. 

The potential problem I see here is when `$Script:DefenderServices` will be set to false by `wscsvc`. Potential edge-case (last service state other than `Running`)
```
Status   Name               DisplayName
------   ----               -----------
Running  Windefend          Microsoft Defender Antivirus Service
Running  SecurityHealthS... Windows Security Service
Stopped  wscsvc             Security Center
```

So basically Sophia uses only **one** flag where state of **3** different services is stored.

Haven't checked how this could actually influence the rest but it looks a bit illogical to me. The same false state will appear when all services are `Stopped` and only last one is `Running`</div>

### PR DESCRIPTION
**Pull request by alan-null**
Fixes #430 
[Test script](https://gist.github.com/alan-null/206e6a3a1d034551d87e928cd59a6792)

### CODE REVIEW

**Comment by farag2** [comment]
```powershell
$Script:DefenderServices = @()
@("Windefend", "SecurityHealthService", "wscsvc") | ForEach-Object -Process {
	if ($null -eq (Get-Service -Name $_ -ErrorAction Ignore))
	{
		$Localization.WindowsBroken
		exit
	}
	else
	{
		if ((Get-Service -Name $_).Status -eq "running")
		{
			$Script:DefenderServices = $true
		}
		else
		{
			$Script:DefenderServices = $false
		}
	}
}

if ($Script:DefenderServices -contains $false)
{
    $Script:DefenderServices = $false
}
else
{
    $Script:DefenderServices = $true
}
$Script:DefenderServices
```

Complicated?

**Comment by farag2** [comment]
```powershell
@("Windefend", "SecurityHealthService", "wscsvc") | ForEach-Object -Process {
	if ($null -eq (Get-Service -Name $_ -ErrorAction Ignore))
	{
		$Localization.WindowsBroken
		exit
	}
	else
	{
		if (((Get-Service -Name $_).Status -eq "running") -ne 0)
		{
			$Script:DefenderServices = $true
		}
		else
		{
			$Script:DefenderServices = $false
		}
	}
}
$Script:DefenderServices
```

Better.

**Comment by alan-null** [comment]
@farag2 It has the same flaw as initial the implementation, see [here](https://gist.github.com/alan-null/206e6a3a1d034551d87e928cd59a6792).

If you don't accept public contributions and want to implement everything alone let me know I won't propose any changes in your code.

**Comment by farag2** [comment]
Yeah, you're right. My approach was wrong.

**Comment by farag2** [comment]
```powershell
try
{
    Get-Service -Name Windefend, SecurityHealthService, wscsvc -ErrorAction Stop
}
catch [System.Object]
{
    $Localization.WindowsBroken
    exit
}

$notRunning = @(Get-Service -Name Windefend, SecurityHealthService, wscsvc | Where-Object -FilterScript {$_.Status -ne "running"})
$Script:DefenderServices = $notRunning.Count -eq 0
```
What do you think?

Please, do not get up steam. Nobody belittling your accomplishments. 👍

**Comment by alan-null** [comment]
Good idea. I made some improvements:
- reduced `Get-Service` calls
- specified exception type

Pushed changes to branch, sorry if I overridden yours. (force push)

**Comment by farag2** [comment]
Why did you use `Microsoft.PowerShell.Commands.ServiceCommandException` if we need to check whether service exist? I offer to use `[System.Object]`.

**Comment by alan-null** [comment]
***@***.***

Alan

**Comment by farag2** [comment]
Correct, correct.

**Comment by farag2** [comment]
Could you re-create the PR. I messed up all code))

**Comment by alan-null** [comment]
@farag2 force-pushed my single commit.

If needed here is a backup of previous branch with your commits
https://github.com/alan-null/Sophia-Script-for-Windows/commits/issue/430_wip

**Pull request merged**
