### PR TITLE
Added Polish translation

### PR DESCRIPTION
**Pull request by alan-null**

### CODE REVIEW

**Comment by lowl1f3** [comment]
Hi. You forgot to translate this file: https://github.com/farag2/Sophia-Script-for-Windows/pull/424/files#diff-64ebf8878eb166285782c1b063a71a750152ea11f49df1ec4596a6327f1b226a
😸

**Comment by alan-null** [comment]
@lowl1f3 done, thanks for heads up :)

**Comment by farag2** [comment]
Thanks a lot! Will approve tomorrow. :) What so you about translating also SophiApp? 😸

**Comment by alan-null** [comment]
@farag2 Sure but first I need to test/use it - UI translations tend to be "specific" sometimes.

**Comment by farag2** [comment]
It will be pretty difficult for you, because you need a special code to implement new strings into the main JSON, then fork it and create a new release to trigger compilation.

https://github.com/farag2/Utilities/blob/master/JSON/Compare_JSONs_and_merge_them_into_one.ps1

**Comment by alan-null** [comment]
We will figure it out. Thanks for the info .

**Comment by alan-null** [comment]
@farag2 Thanks.

**Pull request merged**
